### ISSUE TITLE
Advanced World Generation (Taking over for #3)

### ISSUE THREAD

**Issue by Kassicus** [Kassicus/project-dawn#11]

**Comment by Kassicus** [comment]
## ToDo

### world.py
- [x] Finish generating world
- [ ] Collision detection with world borders
- [ ] Create door class
- [ ] Door collisions and changing rooms

### player.py
- [x] Change player facing system to face mouse cursor
- [ ] Tweak movement to be more fluid (include friction and spool up/down
- [x] Convert player to a sprite

### particle.py
- [x] Change fire particle to be top down?
- [ ] Change impact particle to be more dynamic (maybe top down)

**Comment by Kassicus** [comment]
This was replaced due to changed made in #17, because of that this is no longer necessary
